<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE module [
<!ELEMENT module (short, desc, (func|class)*)>
<!ATTLIST module name CDATA #REQUIRED>
<!ELEMENT short (#PCDATA)>
<!ELEMENT desc (#PCDATA)>
<!ELEMENT call (#PCDATA)>
<!ELEMENT func (call, desc)>
<!ATTLIST func name CDATA #REQUIRED>
<!ELEMENT class (constructor, desc, (attr|method)*)>
<!ATTLIST class name CDATA #REQUIRED>
<!ELEMENT constructor (#PCDATA)>
<!ELEMENT attr (#PCDATA)>
<!ATTLIST attr name CDATA #REQUIRED>
<!ELEMENT method (call, desc)>
<!ATTLIST method name CDATA #REQUIRED>
]>

<module name="pygame2.sdlmixer.music">
  <short>SDL_mixer music playback</short>
  <desc></desc>

  <func name="fade_out">
    <call></call>
    <desc></desc>
  </func>
  <func name="fading">
    <call></call>
    <desc></desc>
  </func>
  <func name="get_volume">
    <call></call>
    <desc></desc>
  </func>
  <func name="halt">
    <call></call>
    <desc></desc>
  </func>
  <func name="pause">
    <call></call>
    <desc></desc>
  </func>
  <func name="paused">
    <call></call>
    <desc></desc>
  </func>
  <func name="playing">
    <call></call>
    <desc></desc>
  </func>
  <func name="resume">
    <call></call>
    <desc></desc>
  </func>
  <func name="rewind">
    <call></call>
    <desc></desc>
  </func>
  <func name="set_position">
    <call></call>
    <desc></desc>
  </func>
  <func name="set_volume">
    <call></call>
    <desc></desc>
  </func>
</module>

