<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE module [
<!ELEMENT module (short, desc, (func|class)*)>
<!ATTLIST module name CDATA #REQUIRED>
<!ELEMENT short (#PCDATA)>
<!ELEMENT desc (#PCDATA)>
<!ELEMENT call (#PCDATA)>
<!ELEMENT func (call, desc)>
<!ATTLIST func name CDATA #REQUIRED>
<!ELEMENT class (constructor, desc, (attr|method)*)>
<!ATTLIST class name CDATA #REQUIRED>
<!ELEMENT constructor (#PCDATA)>
<!ELEMENT attr (#PCDATA)>
<!ATTLIST attr name CDATA #REQUIRED>
<!ELEMENT method (call, desc)>
<!ATTLIST method name CDATA #REQUIRED>
]>


<module name="pygame2.sdl.video">
  <short>SDL video display wrapper module.</short>
  <desc></desc>

  <class name="Overlay">
    <constructor>TODO</constructor>
    <desc></desc>
    <method name="display">
      <call></call>
      <desc></desc>
    </method>
    <attr name="format"></attr>
    <attr name="h"></attr>
    <attr name="height"></attr>
    <attr name="hw_overlay"></attr>
    <method name="lock">
      <call></call>
      <desc></desc>
    </method>
    <attr name="locked"></attr>
    <attr name="pitches"></attr>
    <attr name="pixels"></attr>
    <attr name="planes"></attr>
    <attr name="size"></attr>
    <method name="unlock">
      <call></call>
      <desc></desc>
    </method>
    <attr name="w"></attr>
    <attr name="width"></attr>
  </class>

  <class name="PixelFormat">
    <constructor>TODO</constructor>
    <desc></desc>
    <attr name="alpha"></attr>
    <attr name="bits_per_pixel"></attr>
    <attr name="bytes_per_pixel"></attr>
    <attr name="colorkey"></attr>
    <method name="get_rgba">
      <call></call>
      <desc></desc>
    </method>
    <attr name="losses"></attr>
    <method name="map_rgba">
      <call></call>
      <desc></desc>
    </method>
    <attr name="masks"></attr>
    <attr name="palette"></attr>
    <attr name="shifts"></attr>
  </class>

  <class name="Surface">
    <constructor>Surface () -> Surface</constructor>
    <desc>Creates a new Surface</desc>
    <method name="blit">
      <call></call>
      <desc></desc>
    </method>
    <attr name="clip_rect"></attr>
    <method name="copy">
      <call></call>
      <desc></desc>
    </method>
    <method name="convert">
      <call></call>
      <desc></desc>
    </method>
    <method name="fill">
      <call></call>
      <desc></desc>
    </method>
    <attr name="flags"></attr>
    <method name="flip">
      <call></call>
      <desc></desc>
    </method>
    <attr name="format"></attr>
    <method name="get_alpha">
      <call></call>
      <desc></desc>
    </method>
    <method name="get_at">
      <call></call>
      <desc></desc>
    </method>
    <method name="get_colorkey">
      <call></call>
      <desc></desc>
    </method>
    <method name="get_palette">
      <call></call>
      <desc></desc>
    </method>
    <attr name="h"></attr>
    <attr name="height"></attr>
    <method name="lock">
      <call></call>
      <desc></desc>
    </method>
    <attr name="locked"></attr>
    <attr name="pitch"></attr>
    <attr name="pixels"></attr>
    <method name="save">
      <call></call>
      <desc></desc>
    </method>
    <method name="set_alpha">
      <call></call>
      <desc></desc>
    </method>
    <method name="set_at">
      <call></call>
      <desc></desc>
    </method>
    <method name="set_colorkey">
      <call></call>
      <desc></desc>
    </method>
    <method name="set_colors">
      <call></call>
      <desc></desc>
    </method>
    <method name="set_palette">
      <call></call>
      <desc></desc>
    </method>
    <attr name="size"></attr>
    <method name="unlock">
      <call></call>
      <desc></desc>
    </method>
    <method name="update">
      <call></call>
      <desc></desc>
    </method>
    <attr name="w"></attr>
    <attr name="width"></attr>
  </class>

  <func name="get_drivername">
    <call></call>
    <desc></desc>
  </func>
  <func name="get_gammaramp">
    <call></call>
    <desc></desc>
  </func>
  <func name="get_info">
    <call></call>
    <desc></desc>
  </func>
  <func name="get_videosurface">
    <call></call>
    <desc></desc>
  </func>
  <func name="init">
    <call></call>
    <desc></desc>
  </func>
  <func name="is_mode_ok">
    <call></call>
    <desc></desc>
  </func>
  <func name="list_modes">
    <call></call>
    <desc></desc>
  </func>
  <func name="quit">
    <call></call>
    <desc></desc>
  </func>
  <func name="set_gamma">
    <call></call>
    <desc></desc>
  </func>
  <func name="set_gammaramp">
    <call></call>
    <desc></desc>
  </func>
  <func name="set_mode">
    <call></call>
    <desc></desc>
  </func>
  <func name="was_init">
    <call></call>
    <desc></desc>
  </func>
</module>

